/**
 * Pre-electron-builder verification: ensure out/ (Next.js static export)
 * exists, so electron-builder doesn't silently produce an asar without the
 * frontend (which causes the "pet not showing" blank-window bug).
 *
 * NOTE: dist-electron/ is checked separately AFTER tsc runs (it's generated
 * by `tsc -p tsconfig.electron.json` which runs after this script in the
 * build chain). Here we only verify the `out/` from `build:desktop`.
 *
 * Exits non-zero if the build is incomplete.
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

const checks = [
  ["out/index.html", "Next.js static export (out/index.html)"],
  ["out/_next", "Next.js static assets (out/_next)"],
  ["out/pets", "Pet sprites (out/pets)"],
  ["data/keepAlive.ps1", "KeepAlive script"],
  ["data/time.json", "Shuttle schedule"],
];

let ok = true;
console.log("→ verifying build artifacts...");
for (const [rel, label] of checks) {
  const full = path.join(root, rel);
  if (fs.existsSync(full)) {
    console.log(`  ✓ ${rel}  (${label})`);
  } else {
    console.error(`  ✗ MISSING: ${rel}  (${label})`);
    ok = false;
  }
}

if (!ok) {
  console.error("\n✗ build verification FAILED — run `bun run build:desktop` first");
  console.error("  electron-builder would produce a broken asar without these files.");
  process.exit(1);
}

// Also count pet sprites to make sure all 24 are there.
const petsDir = path.join(root, "out", "pets");
if (fs.existsSync(petsDir)) {
  const pets = fs.readdirSync(petsDir).filter(f => f.endsWith(".png"));
  console.log(`  ✓ ${pets.length} pet sprites in out/pets/`);
  if (pets.length < 24) {
    console.warn(`  ⚠ expected 24 pets, found ${pets.length}`);
  }
}

// Warn (not fail) if dist-electron is missing — it'll be generated by tsc next.
const distElectron = path.join(root, "dist-electron", "main.js");
if (fs.existsSync(distElectron)) {
  console.log(`  ✓ dist-electron/main.js (already compiled)`);
} else {
  console.log(`  ℹ dist-electron/ not yet built (tsc will run next)`);
}

console.log("✓ build verification passed\n");
